image: docker/compose
pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        caches:
          - node
        script:
          - docker-compose -f docker-compose.demo.yml up -d
          - npm run test:e2e