image: node:12.14.1
pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        caches:
          - node
        script:
          - npm install
          - npm run build
          - docker-compose -f docker-compose.local.yml up -d
          - npm run test:e2e