image: docker/compose
pipelines:
  pull-requests:
    '**':
      - step:
          name: Build Images
          services:
            - docker
          caches:
            - node
          script:
            - docker-compose -f docker-compose.test.yml up -d
            - apk add --update nodejs npm
            - npm install
            - docker container logs test_openbox_api
            - curl http://localhost:8001
            - npm run test:e2e