image: docker/compose
pipelines:
  default:
    - step:
        name: Build Images
        services:
          - docker
        caches:
          - node
        script:
          - docker-compose -f docker-compose.test.yml up -d
          - docker container ls
          - apk add --update nodejs npm
          - node -v
          - npm -v
          - npm install
          - npm run test:e2e