version: "3.1"

services:
  openbox_db:
    image: postgres:12.3
    ports:
      - "3001:5432"
    env_file:
      - prod.env
    volumes:
      - openbox_database:/var/lib/postgresql/data

  openbox_api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - prod.env
    depends_on:
      - openbox_db

volumes:
  openbox_database: {}