version: '3.1'

services:
  dev_openbox_db:
    container_name: dev_openbox_db
    image: postgres:13.1-alpine
    ports:
      - '9000:5432'
    env_file:
      - dev.env
    volumes:
      - dev_openbox_database:/var/lib/postgresql/data

  dev_openbox_api:
    container_name: dev_openbox_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9001:3000'
    env_file:
      - dev.env
    depends_on:
      - dev_openbox_db

volumes:
  dev_openbox_database: {}
