version: "3.1"

services:
  dev_openbox_db:
    image: postgres:13.1-alpine
    ports:
      - "3001:5432"
    environment:
      - dev.env
    volumes:
      - dev_openbox_database:/var/lib/postgresql/data

  dev_openbox_api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - dev.env
    depends_on:
      - dev_openbox_db

volumes:
  dev_openbox_database: {}