version: '3.1'

services:
  demo_openbox_db:
    container_name: demo_openbox_db
    image: postgres:13.1-alpine
    ports:
      - '8000:5432'
    env_file:
      - test.env
    volumes:
      - demo_openbox_database:/var/lib/postgresql/data
      - ./local.init:/docker-entrypoint-initdb.d

  demo_openbox_api:
    container_name: demo_openbox_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:3000'
    env_file:
      - test.env
    depends_on:
      - demo_openbox_db

volumes:
  demo_openbox_database: {}
