const { EntitySchema } = require("typeorm");

module.exports = new EntitySchema({
  name: "Invoice",
  columns: {
    id: { type: "uuid", generated: "uuid", primary: true },
    authorization: { type: "varchar", nullable: false },
    sequence: { type: "varchar", nullable: false },
    invoiceDate: { type: "date", nullable: true },
    customerName: { type: "varchar", nullable: true },
    customerAddress1: { type: "varchar", nullable: true },
    customerAddress2: { type: "varchar", nullable: true },
    customerCountry: { type: "varchar", nullable: true },
    customerState: { type: "varchar", nullable: true },
    customerCity: { type: "varchar", nullable: true },
    customerDui: { type: "varchar", nullable: true },
    customerNit: { type: "varchar", nullable: true },
    customerNrc: { type: "varchar", nullable: true },
    customerGiro: { type: "varchar", nullable: true },
    paymentConditionName: { type: "varchar", nullable: true },
    sellerName: { type: "varchar", nullable: true },
    zoneName: { type: "varchar", nullable: true },
    sum: { type: "decimal", nullable: true },
    iva: { type: "decimal", nullable: true },
    subtotal: { type: "decimal", nullable: true },
    ivaRetenido: { type: "decimal", nullable: true },
    ventasExentas: { type: "decimal", nullable: true },
    ventasNoSujetas: { type: "decimal", nullable: true },
    ventaTotal: { type: "decimal", nullable: true },
    ventaTotalText: { type: "varchar", nullable: true },
    printedDate: { type: "timestamp", nullable: true },
    createdAt: { type: "timestamp", createDate: true },
    updatedAt: { type: "timestamp", updateDate: true },
  },
  relations: {
    company: {
      target: "Company",
      type: "many-to-one",
      joinTable: true,
    },
    branch: {
      target: "Branch",
      type: "many-to-one",
      joinTable: true,
    },
    customer: {
      target: "Customer",
      type: "many-to-one",
      joinTable: true,
    },
    customerBranch: {
      target: "CustomerBranch",
      type: "many-to-one",
      joinTable: true,
    },
    customerType: {
      target: "CustomerType",
      type: "many-to-one",
      joinTable: true,
    },
    customerTypeNatural: {
      target: "CustomerTypeNatural",
      type: "many-to-one",
      joinTable: true,
    },
    documentType: {
      target: "InvoicesDocumentType",
      type: "many-to-one",
      joinTable: true,
    },
    invoicesPaymentsCondition: {
      target: "InvoicesPaymentsCondition",
      type: "many-to-one",
      joinTable: true,
    },
    invoicesSeller: {
      target: "InvoicesSeller",
      type: "many-to-one",
      joinTable: true,
    },
    invoicesZone: {
      target: "InvoicesZone",
      type: "many-to-one",
      joinTable: true,
    },
    status: {
      target: "InvoicesStatus",
      type: "many-to-one",
      joinTable: true,
    },
    details: {
      target: "InvoiceDetail",
      type: "one-to-many",
      joinTable: true,
      joinColumn: true,
      inverseSide: "invoice",
    },
  },
});
